apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
