kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devops-3

networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443


nodes:
- role: control-plane
  image: kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f
  extraPortMappings:
      # Gateway / ingress HTTP
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP

      # Frontend 
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP

      # Backend 
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP

- role: worker
  image: kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f
  labels:
      node-role: backend

- role: worker
  image: kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f
  labels:
      node-role: frontend
